export const PAGINAS = [
  'home',
  'ferramentas-oracle',
  'patrimonio',
  'empresas',
  'colaboradores',
  'contacorrente',
  'contacorrentetodos',
  'caixaviagem',
  'caixaviagemtodos',
  'usuarios',
  'permissoes',
  'contratos',
  'manuais',
  'ncm',
  'relatorios',
  'banco-de-horas',
  'ponto',
  'aniversariantes',
  'tabelas-lh',
  'estoque',
  'extratos',
  'eventos',
  'gerador-recibo',
  'tabela-de-preco',
  'epi',
  'precificador',
  'simulacao-financeira',
] as const

export type Pagina = (typeof PAGINAS)[number]
